import { collection, doc, getDocs, query, setDoc, updateDoc } from "firebase/firestore";
import { db } from "./firebase";
import { useEffect, useState } from "react";

const MIN_LIMIT=0,MAX_LIMIT=100000;
function makeToken(){const bytes=crypto.getRandomValues(new Uint8Array(18));return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");}
export default function AccessRequestsAdmin(){
 const [items,setItems]=useState([]),[users,setUsers]=useState([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const[r,u]=await Promise.all([getDocs(query(collection(db,"accessRequests"))),getDocs(query(collection(db,"users")))]);setItems(r.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.requestedAt?.seconds||0)-(a.requestedAt?.seconds||0)));setUsers(u.docs.map(d=>({id:d.id,...d.data()})));}catch(e){console.error(e);setError("Could not load access management data.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 function findUser(item){return users.find(u=>u.id===item.uid||u.email?.toLowerCase()===item.email?.toLowerCase());}
 async function status(item,nextStatus){setError("");setMessage("");try{const u=findUser(item);await updateDoc(doc(db,"accessRequests",item.id),{status:nextStatus,reviewedAt:new Date()});if(u){await setDoc(doc(db,"users",u.id),{active:nextStatus==="Granted",maxChars:nextStatus==="Granted"?Number(item.adminLimit??u.maxChars??1000):1000,status:nextStatus,email:u.email||item.email},{merge:true});}setMessage(`${item.email}: ${nextStatus}.`);await load();}catch(e){console.error(e);setError("Could not update this request.");}}
 async function editLimit(item){const u=findUser(item);const raw=window.prompt(`Character limit for ${item.email} (0–100,000)`,String(item.adminLimit??u?.maxChars??1000));if(raw===null)return;const value=Number(raw);if(!Number.isInteger(value)||value<MIN_LIMIT||value>MAX_LIMIT)return setError("Enter a whole number between 0 and 100,000.");try{if(u){await setDoc(doc(db,"users",u.id),{uid:u.id,email:u.email||item.email,maxChars:value,active:true,status:"Granted",limitUpdatedAt:new Date()},{merge:true});await updateDoc(doc(db,"accessRequests",item.id),{adminLimit:value,status:"Granted",reviewedAt:new Date(),uid:u.id});}else{await updateDoc(doc(db,"accessRequests",item.id),{adminLimit:value});}setMessage(`Limit set to ${value.toLocaleString()} for ${item.email}.`);await load();}catch(e){console.error(e);setError("Could not set the character limit.");}}
 async function invite(item){const value=Number(item.adminLimit??1000);if(!Number.isInteger(value)||value<MIN_LIMIT||value>MAX_LIMIT)return setError("Set a valid limit between 0 and 100,000 before inviting.");try{const id=makeToken();await setDoc(doc(db,"accessInvites",id),{email:item.email.toLowerCase(),maxChars:value,requestId:item.id,used:false,createdAt:new Date(),expiresAt:Date.now()+604800000});await updateDoc(doc(db,"accessRequests",item.id),{status:"Granted",adminLimit:value,inviteId:id,invitedAt:new Date()});const url=`${window.location.origin}/?invite=${id}`;await navigator.clipboard.writeText(url);setMessage(`Invitation copied for ${item.email}. Valid for 7 days.`);await load();}catch(e){console.error(e);setError("Could not create invitation.");}}
 async function revoke(item){const u=findUser(item);if(!u)return setError("This user has not created an account yet.");if(!window.confirm(`Revoke extended access for ${item.email}?`))return;try{await setDoc(doc(db,"users",u.id),{active:false,maxChars:1000,status:"Revoked",revokedAt:new Date()},{merge:true});await updateDoc(doc(db,"accessRequests",item.id),{status:"Denied",revokedAt:new Date(),uid:u.id});setMessage(`Access revoked for ${item.email}.`);await load();}catch(e){console.error(e);setError("Could not revoke access.");}}
 return <section className="admin-section access-requests-section"><style>{`.access-requests-section .request-actions{display:flex;align-items:flex-end;gap:8px;flex-wrap:wrap}.access-requests-section .request-actions .primary-button,.access-requests-section .request-actions .secondary-button{width:auto;min-height:40px;height:40px;padding:0 14px;border-radius:10px;font-size:13px}.access-requests-section .request-actions .status-select-label{display:flex;flex-direction:column;gap:5px;margin:0;font-size:11px;font-weight:600;color:#666}.access-requests-section .request-actions .admin-status-select{width:148px;height:40px;min-height:40px;margin:0;padding:0 10px;border-radius:10px;font-size:13px;background:#fff}.access-requests-section .request-actions .primary-button:hover,.access-requests-section .request-actions .secondary-button:hover{transform:none}.access-requests-section .admin-refresh{width:auto!important}`}</style><div className="admin-section-heading"><div><h2>Extended access</h2><p>Approve users, issue invitations, edit limits, and revoke access.</p></div><button className="secondary-button admin-refresh" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>{error&&<div className="admin-error">{error}</div>}{message&&<div className="admin-success">{message}</div>}{items.length===0?<p className="admin-muted">No requests yet.</p>:<div className="request-list">{items.map(item=>{const u=findUser(item),current=Number(item.adminLimit??u?.maxChars??1000),statusValue=item.status||"Pending";return <article className="request-card" key={item.id}><div className="request-card-top"><div><strong>{item.name}</strong><span>{item.email}</span></div><span className={`request-status status-${String(statusValue).toLowerCase()}`}>{statusValue}</span></div><p>{item.purpose}</p><div className="request-meta"><span>Account: {u?(u.active===false?"Revoked":"Created"):"Not created"}</span><span>Limit: {current.toLocaleString()}</span></div><div className="request-actions"><label className="status-select-label">Status<select className="admin-status-select" value={statusValue} onChange={e=>status(item,e.target.value)}><option value="Pending">Pending</option><option value="Denied">Denied</option><option value="Granted">Granted</option></select></label><button className="primary-button" onClick={()=>editLimit(item)}>Edit limit</button>{statusValue==="Granted"&&!u&&<button className="primary-button" onClick={()=>invite(item)}>Invite</button>}{u&&u.active!==false&&<button className="secondary-button" onClick={()=>revoke(item)}>Revoke</button>}</div></article>})}</div>}</section>;
}
