import { useEffect, useState } from "react";
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from "firebase/auth";
import { collection, doc, getCountFromServer, getDocs, getDoc, limit, query, serverTimestamp, setDoc, Timestamp, where, writeBatch } from "firebase/firestore";
import { auth, db } from "./firebase";
import AccessRequestsAdmin from "./AccessRequestsAdmin";

const CLEANUP_BATCH_SIZE = 499;
const EXPIRY_TYPES = [["1m", "1 minute"], ["5m", "5 minutes"], ["10m", "10 minutes"], ["30m", "30 minutes"], ["1h", "1 hour"], ["6h", "6 hours"], ["12h", "12 hours"], ["24h", "24 hours"], ["7d", "7 days"], ["forever", "Forever"]];
const metricsRef = doc(db, "adminMetrics", "global");
const EMPTY = { current: 0, expired: 0, totalCreated: 0, totalDeleted: 0, totalViews: 0, createdToday: 0, createdWeek: 0, byExpiry: [], legacy: 0, locked: 0, unlocked: 0, currentLocked: 0, currentUnlocked: 0, legacySecurity: 0, lastCleanupAt: null };

export default function AdminPage() {
  const [user, setUser] = useState(undefined), [isAdmin, setIsAdmin] = useState(false), [email, setEmail] = useState(""), [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false), [checking, setChecking] = useState(true), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [expiredCount, setExpiredCount] = useState(null), [metrics, setMetrics] = useState(EMPTY), [tab, setTab] = useState("stats");

  useEffect(() => onAuthStateChanged(auth, async (currentUser) => { setUser(currentUser); setIsAdmin(false); setChecking(true); if (!currentUser) return setChecking(false); try { const snap = await getDoc(doc(db, "admins", currentUser.uid)); setIsAdmin(snap.exists() && snap.data().enabled === true); } catch { setError("Could not verify admin access."); } finally { setChecking(false); } }), []);
  useEffect(() => { if (isAdmin && tab === "stats") refreshMetrics(); }, [isAdmin, tab]);

  async function handleLogin(event) { event.preventDefault(); setError(""); setLoading(true); try { await signInWithEmailAndPassword(auth, email.trim(), password); setPassword(""); } catch { setError("Invalid email or password."); } finally { setLoading(false); } }
  async function handleLogout() { await signOut(auth); }

  async function refreshMetrics() {
    setError(""); setLoading(true);
    try {
      const clipsRef = collection(db, "clips"), eventsRef = collection(db, "clipCreationEvents"), now = Date.now();
      const [currentSnap, expiredSnap, historicalSnap, storedSnap, clipDocs] = await Promise.all([getCountFromServer(clipsRef), getCountFromServer(query(clipsRef, where("expiresAt", "<=", now))), getCountFromServer(eventsRef), getDoc(metricsRef), getDocs(clipsRef)]);
      const current = currentSnap.data().count, expired = expiredSnap.data().count, historicalEvents = historicalSnap.data().count, stored = storedSnap.exists() ? storedSnap.data() : {}, totalDeleted = Number(stored.totalDeleted || 0), totalCreated = Math.max(historicalEvents, current + totalDeleted);
      const totalViews = clipDocs.docs.reduce((sum, d) => sum + Number(d.data().views || 0), 0), currentLocked = clipDocs.docs.filter((d) => d.data().protected === true).length, currentUnlocked = clipDocs.docs.length - currentLocked;
      const [lockedSnap, unlockedSnap] = await Promise.all([getCountFromServer(query(eventsRef, where("protected", "==", true))), getCountFromServer(query(eventsRef, where("protected", "==", false)))]);
      const locked = lockedSnap.data().count, unlocked = unlockedSnap.data().count, legacySecurity = Math.max(0, totalCreated - locked - unlocked);
      const todayStart = new Date(); todayStart.setHours(0, 0, 0, 0); const weekStart = new Date(todayStart); weekStart.setDate(weekStart.getDate() - 6);
      const [todaySnap, weekSnap] = await Promise.all([getCountFromServer(query(eventsRef, where("createdAt", ">=", Timestamp.fromDate(todayStart)))), getCountFromServer(query(eventsRef, where("createdAt", ">=", Timestamp.fromDate(weekStart))))]);
      const byExpiry = await Promise.all(EXPIRY_TYPES.map(async ([key, label]) => ({ key, label, count: (await getCountFromServer(query(eventsRef, where("expirationType", "==", key)))).data().count })));
      const knownHistorical = byExpiry.reduce((sum, item) => sum + item.count, 0);
      setExpiredCount(expired); setMetrics({ current, expired, totalCreated, totalDeleted, totalViews, createdToday: todaySnap.data().count, createdWeek: weekSnap.data().count, byExpiry, legacy: Math.max(0, totalCreated - knownHistorical), locked, unlocked, currentLocked, currentUnlocked, legacySecurity, lastCleanupAt: stored.lastCleanupAt || null });
    } catch (err) { console.error(err); setError("Could not load metrics. Check your Firestore rules and publish the latest rules."); } finally { setLoading(false); }
  }

  async function backfillExistingClips() {
    setError(""); setMessage(""); setLoading(true);
    try { const snapshot = await getDocs(collection(db, "clips")); let added = 0; for (let start = 0; start < snapshot.docs.length; start += CLEANUP_BATCH_SIZE) { const batch = writeBatch(db); const page = snapshot.docs.slice(start, start + CLEANUP_BATCH_SIZE); for (const clip of page) { const data = clip.data(); batch.set(doc(db, "clipCreationEvents", clip.id), { code: clip.id, createdAt: data.createdAt || serverTimestamp(), expirationType: data.expirationType || "legacy", expirationLabel: data.expirationLabel || "Legacy / unspecified", protected: data.protected === true }, { merge: true }); } await batch.commit(); added += page.length; } setMessage(`Historical baseline updated for ${added} stored clip${added === 1 ? "" : "s"}.`); await refreshMetrics(); } catch (err) { console.error(err); setError("Could not backfill existing clips."); } finally { setLoading(false); }
  }
  async function findExpired() { setError(""); setMessage(""); setLoading(true); try { const snap = await getDocs(query(collection(db, "clips"), where("expiresAt", "<=", Date.now()), limit(CLEANUP_BATCH_SIZE))); setExpiredCount(snap.size); setMessage(snap.size === 0 ? "No expired clips found." : `Found ${snap.size} expired clip${snap.size === 1 ? "" : "s"}.`); } catch { setError("Could not query expired clips."); } finally { setLoading(false); } }
  async function clearExpired() { setError(""); setMessage(""); setExpiredCount(null); setLoading(true); let deleted = 0; try { while (true) { const snap = await getDocs(query(collection(db, "clips"), where("expiresAt", "<=", Date.now()), limit(CLEANUP_BATCH_SIZE))); if (snap.empty) break; const batch = writeBatch(db); snap.docs.forEach((clip) => batch.delete(clip.ref)); await batch.commit(); deleted += snap.size; } if (deleted) { const currentMetrics = await getDoc(metricsRef); const oldDeleted = currentMetrics.exists() ? Number(currentMetrics.data().totalDeleted || 0) : 0; await setDoc(metricsRef, { totalDeleted: oldDeleted + deleted, lastCleanupAt: serverTimestamp() }, { merge: true }); } setExpiredCount(0); setMessage(deleted ? `Deleted ${deleted} expired clip${deleted === 1 ? "" : "s"}.` : "No expired clips needed to be deleted."); } catch (err) { console.error(err); setError(deleted ? `Cleanup stopped after deleting ${deleted} clips.` : "Cleanup failed."); } finally { setLoading(false); if (tab === "stats") refreshMetrics(); } }

  if (checking) return <AdminShell><p>Checking admin access…</p></AdminShell>;
  if (!user) return <AdminShell centered><div className="admin-badge">ARCHICLIP ADMIN</div><h1>Admin login</h1><p className="admin-muted">Sign in with the administrator Firebase account.</p><div className="admin-login-form-wrap"><form className="admin-form" onSubmit={handleLogin}><label htmlFor="admin-email">Email</label><input id="admin-email" type="email" autoComplete="username" value={email} onChange={(e) => setEmail(e.target.value)} required /><label htmlFor="admin-password">Password</label><input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required />{error && <div className="admin-error">{error}</div>}<button className="primary-button create-button" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</button></form></div></AdminShell>;
  if (!isAdmin) return <AdminShell><div className="admin-badge">ACCESS DENIED</div><h1>Not an administrator</h1><p className="admin-muted">This Firebase account is authenticated but has not been granted ArchiClip admin access.</p><button className="primary-button" onClick={handleLogout}>Sign out</button></AdminShell>;

  return <AdminShell>
    <div className="admin-topbar"><div><div className="admin-badge">ARCHICLIP ADMIN</div><h1>Dashboard</h1></div><button className="secondary-button" onClick={handleLogout}>Sign out</button></div>
    <nav className="admin-tabs" aria-label="Admin sections"><button className={tab === "stats" ? "active" : ""} onClick={() => { setTab("stats"); setError(""); setMessage(""); }}>Stats</button><button className={tab === "controls" ? "active" : ""} onClick={() => { setTab("controls"); setError(""); setMessage(""); }}>Controls</button><button className={tab === "users" ? "active" : ""} onClick={() => { setTab("users"); setError(""); setMessage(""); }}>Users</button></nav>
    {tab === "stats" && <StatsTab metrics={metrics} loading={loading} refreshMetrics={refreshMetrics} />}
    {tab === "controls" && <ControlsTab expiredCount={expiredCount} metrics={metrics} loading={loading} error={error} message={message} findExpired={findExpired} clearExpired={clearExpired} backfillExistingClips={backfillExistingClips} />}
    {tab === "users" && <AccessRequestsAdmin />}
  </AdminShell>;
}

function StatsTab({ metrics, loading, refreshMetrics }) { return <div className="admin-tab-content"><p className="admin-muted">Usage and lifetime metrics only.</p><div className="admin-metrics-grid"><MetricCard label="Total created" value={metrics.totalCreated} detail="Lifetime" /><MetricCard label="Currently stored" value={metrics.current} detail="In Firestore" /><MetricCard label="Total deleted" value={metrics.totalDeleted} detail="Admin cleanup" /><MetricCard label="Total views" value={metrics.totalViews} detail="Stored clips" /></div><div className="admin-metrics-grid admin-metrics-secondary"><MetricCard label="Created today" value={metrics.createdToday} detail="Since midnight" /><MetricCard label="Created this week" value={metrics.createdWeek} detail="Last 7 days" /><MetricCard label="Expired pending" value={metrics.expired} detail="Unavailable to users" /><MetricCard label="View rate" value={metrics.totalCreated ? `${((metrics.totalViews / metrics.totalCreated) * 100).toFixed(1)}%` : "0%"} detail="Views / created" /></div><section className="admin-section"><div className="admin-section-heading"><div><h2>Lifetime clips by security</h2><p>All clips created since tracking began, including deleted clips.</p></div></div><div className="expiry-grid"><div className="expiry-row"><span>🔒 Locked / password protected</span><strong>{metrics.locked.toLocaleString()}</strong></div><div className="expiry-row"><span>🔓 Unlocked / no password</span><strong>{metrics.unlocked.toLocaleString()}</strong></div>{metrics.legacySecurity > 0 && <div className="expiry-row expiry-row-muted"><span>Legacy / security unspecified</span><strong>{metrics.legacySecurity.toLocaleString()}</strong></div>}</div></section><section className="admin-section"><div className="admin-section-heading"><div><h2>Currently stored by security</h2><p>Only clips that still exist in Firestore.</p></div></div><div className="expiry-grid"><div className="expiry-row"><span>🔒 Locked / password protected</span><strong>{metrics.currentLocked.toLocaleString()}</strong></div><div className="expiry-row"><span>🔓 Unlocked / no password</span><strong>{metrics.currentUnlocked.toLocaleString()}</strong></div></div></section><section className="admin-section"><div className="admin-section-heading"><div><h2>Lifetime clips by expiry</h2><p>Every clip created since ArchiClip started.</p></div><button className="secondary-button admin-refresh" onClick={refreshMetrics} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button></div><div className="expiry-grid">{metrics.byExpiry.map((item) => <div className="expiry-row" key={item.key}><span>{item.label}</span><strong>{item.count.toLocaleString()}</strong></div>)}{metrics.legacy > 0 && <div className="expiry-row expiry-row-muted"><span>Legacy / unspecified</span><strong>{metrics.legacy.toLocaleString()}</strong></div>}</div></section></div>; }

function ControlsTab({ expiredCount, metrics, loading, error, message, findExpired, clearExpired, backfillExistingClips }) { return <div className="admin-tab-content"><p className="admin-muted">Administrative actions and maintenance.</p><section className="admin-section cleanup-section"><div className="admin-section-heading"><div><h2>Cleanup expired clips</h2><p>Expired clips are already inaccessible. Cleanup permanently removes them.</p></div></div>{error && <div className="admin-error">{error}</div>}{message && <div className="admin-success">{message}</div>}<div className="admin-stat"><span>Expired clips ready for deletion</span><strong>{expiredCount ?? metrics.expired}</strong></div><div className="admin-actions"><button className="secondary-button" onClick={findExpired} disabled={loading}>Check expired</button><button className="primary-button" onClick={clearExpired} disabled={loading}>{loading ? "Cleaning…" : "Delete expired clips"}</button></div><div className="admin-warning"><strong>This is permanent.</strong> Deleted clips cannot be restored.</div>{metrics.lastCleanupAt && <p className="admin-last-cleanup">Last cleanup: {formatDate(metrics.lastCleanupAt)}</p>}</section><section className="admin-section"><div className="admin-section-heading"><div><h2>Historical data</h2><p>Use this once for clips that existed before lifetime tracking.</p></div></div><button className="secondary-button" onClick={backfillExistingClips} disabled={loading}>Backfill existing clips</button></section></div>; }
function MetricCard({ label, value, detail }) { return <div className="admin-metric-card"><span>{label}</span><strong>{Number.isFinite(Number(value)) ? Number(value).toLocaleString() : value}</strong><small>{detail}</small></div>; }
function formatDate(value) { if (!value) return "—"; const date = typeof value.toDate === "function" ? value.toDate() : new Date(value); return date.toLocaleString(); }
function AdminShell({ children, centered = false }) { return <div className="app admin-app"><main className="container admin-container"><header className="header"><button className="logo" aria-label="ArchiClip home" onClick={() => { window.location.href = "/"; }}><img className="logo-image" src="/archiclip-logo.svg" alt="" aria-hidden="true" /><span>ArchiClip</span></button><span className="header-tag">Administration</span></header><section className={`card admin-card${centered ? " admin-login-card" : ""}`} style={centered ? { textAlign: "center" } : undefined}>{centered && <style>{`.admin-login-card { max-width: 520px; margin-top: 110px; } .admin-login-card .admin-muted { max-width: 390px; margin-left: auto; margin-right: auto; } .admin-login-form-wrap { width: min(100%, 390px); margin: 28px auto 0; text-align: left; }`}</style>}{children}</section></main></div>; }
