import { useEffect, useState } from "react";
import { doc, getDoc, increment, serverTimestamp, updateDoc, writeBatch } from "firebase/firestore";
import { QRCodeSVG } from "qrcode.react";
import { db } from "./firebase";
import AdminPage from "./AdminPage";
import ReceiveWidget from "./ReceiveWidget";

const CODE_LENGTH = 6;
const MAX_TEXT = 10000;
const EXPIRATION_OPTIONS = [
  { key: "1m", label: "1 minute", value: 60000 }, { key: "5m", label: "5 minutes", value: 300000 },
  { key: "10m", label: "10 minutes", value: 600000 }, { key: "30m", label: "30 minutes", value: 1800000 },
  { key: "1h", label: "1 hour", value: 3600000 }, { key: "6h", label: "6 hours", value: 21600000 },
  { key: "12h", label: "12 hours", value: 43200000 }, { key: "24h", label: "24 hours", value: 86400000 },
  { key: "7d", label: "7 days", value: 604800000 }, { key: "forever", label: "Forever", value: null }
];
function generateCode() { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let r = ""; for (let i = 0; i < CODE_LENGTH; i++) r += chars[Math.floor(Math.random() * chars.length)]; return r; }
function b64(bytes) { let s = ""; bytes.forEach((b) => s += String.fromCharCode(b)); return btoa(s); }
function bytes(value) { return Uint8Array.from(atob(value), (c) => c.charCodeAt(0)); }
async function encryptText(text, password) { const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const material = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]); const key = await crypto.subtle.deriveKey({ name: "PBKDF2", salt, iterations: 150000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt"]); const encrypted = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(text)); return { ciphertext: b64(new Uint8Array(encrypted)), salt: b64(salt), iv: b64(iv) }; }
async function decryptText(ciphertext, password, salt, iv) { const material = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]); const key = await crypto.subtle.deriveKey({ name: "PBKDF2", salt: bytes(salt), iterations: 150000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["decrypt"]); const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: bytes(iv) }, key, bytes(ciphertext)); return new TextDecoder().decode(plain); }

function App() {
  const isAdminPath = window.location.pathname === "/admin" || window.location.pathname === "/admin/";
  const [text, setText] = useState(""), [expirationKey, setExpirationKey] = useState("10m"), [password, setPassword] = useState("");
  const [clip, setClip] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState(""), [pathCode, setPathCode] = useState(null);
  useEffect(() => { const path = window.location.pathname; if (path.startsWith("/c/")) { const code = path.replace("/c/", "").split("/")[0].trim().toUpperCase(); if (code) setPathCode(code); } }, []);
  async function createClip() {
    setError(""); if (!text.trim()) return setError("Please enter some text first."); if (text.length > MAX_TEXT) return setError(`Text is limited to ${MAX_TEXT.toLocaleString()} characters.`); if (password && password.length < 4) return setError("Password must be at least 4 characters."); setLoading(true);
    try {
      const expiration = EXPIRATION_OPTIONS.find((o) => o.key === expirationKey) || EXPIRATION_OPTIONS[2]; let code = generateCode(); let clipRef = doc(db, "clips", code); let existing = await getDoc(clipRef); let attempts = 0;
      while (existing.exists() && attempts < 10) { code = generateCode(); clipRef = doc(db, "clips", code); existing = await getDoc(clipRef); attempts++; }
      if (existing.exists()) throw new Error("Could not generate a unique code.");
      const encrypted = password ? await encryptText(text, password) : null; const batch = writeBatch(db); const eventRef = doc(db, "clipCreationEvents", code);
      batch.set(clipRef, { code, content: encrypted ? encrypted.ciphertext : text, createdAt: serverTimestamp(), expiresAt: expiration.value === null ? null : Date.now() + expiration.value, expirationType: expiration.key, expirationLabel: expiration.label, views: 0, protected: Boolean(password), salt: encrypted?.salt || null, iv: encrypted?.iv || null });
      batch.set(eventRef, { code, createdAt: serverTimestamp(), expirationType: expiration.key, expirationLabel: expiration.label }); await batch.commit();
      setClip({ code, content: text, expiresAt: expiration.value === null ? null : Date.now() + expiration.value, protected: Boolean(password) }); setPassword(""); window.history.pushState({}, "", `/c/${code}`);
    } catch (err) { console.error(err); setError("Something went wrong. Please try again."); } finally { setLoading(false); }
  }
  function reset() { setText(""); setClip(null); setError(""); setPathCode(null); setPassword(""); window.history.pushState({}, "", "/"); }
  async function copyText(value) { try { await navigator.clipboard.writeText(value); } catch { setError("Could not access your clipboard."); } }
  async function shareClip() { const url = window.location.href; if (navigator.share) { try { await navigator.share({ title: "ArchiClip", text: "Open this shared text", url }); } catch {} } else { await copyText(url); alert("Link copied!"); } }
  if (isAdminPath) return <AdminPage />; if (pathCode && !clip) return <ClipViewer code={pathCode} onHome={reset} />;
  if (clip) { const shareUrl = `${window.location.origin}/c/${clip.code}`; return <div className="app"><main className="container"><Header /><section className="card success-card"><div className="success-icon">✓</div><h1>Your clip is ready</h1><p className="muted">{clip.protected ? "Protected clip. Share the password separately." : "Open this link on another device or share it with someone."}</p><div className="code-box">{clip.code}</div><div className="qr-wrapper"><QRCodeSVG value={shareUrl} size={190} level="M" /></div><div className="share-url">{shareUrl}</div><Countdown expiresAt={clip.expiresAt} /><div className="button-row"><button className="primary-button" onClick={() => copyText(shareUrl)}>Copy Link</button><button className="secondary-button" onClick={shareClip}>Share</button></div>{clip.protected && <div className="security-note">🔒 Encrypted in your browser. ArchiClip never stores your password.</div>}<button className="text-button" onClick={reset}>Create another clip</button></section></main></div>; }
  return <div className="app"><main className="container"><Header /><section className="hero"><div className="badge">FAST • PRIVATE • SIMPLE</div><h1>Send text<br /><span>instantly.</span></h1><p>Paste something here, get a link, and open it anywhere. No account required.</p></section><section className="card"><span className="small-label">CREATE A CLIP</span><label htmlFor="clip-text">Your text</label><textarea id="clip-text" value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste text, links, notes, commands..." maxLength={MAX_TEXT} /><div className="textarea-footer"><span>{text.length.toLocaleString()} / {MAX_TEXT.toLocaleString()}</span></div><label htmlFor="expiration">Expires after</label><select id="expiration" value={expirationKey} onChange={(e) => setExpirationKey(e.target.value)}>{EXPIRATION_OPTIONS.map((o) => <option key={o.key} value={o.key}>{o.label}</option>)}</select><label htmlFor="clip-password">Password <span className="optional">(optional)</span></label><input id="clip-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Leave blank for a normal clip" autoComplete="new-password" />{password && <div className="security-note compact">🔒 Encrypted before upload.</div>}{error && <div className="error">{error}</div>}<button className="primary-button create-button" onClick={createClip} disabled={loading}>{loading ? "Creating..." : "Create Clip"}</button></section><ReceiveWidget /><section className="features"><Feature icon="⚡" title="Instant" text="Create a shareable clip in seconds." /><Feature icon="🔒" title="Private" text="Optionally encrypt clips with a password." /><Feature icon="📷" title="Scan" text="Open a clip by scanning its QR code." /></section><Footer /></main></div>;
}

function ClipViewer({ code, onHome }) {
  const [clip, setClip] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [password, setPassword] = useState(""), [unlocking, setUnlocking] = useState(false);
  useEffect(() => { (async () => { try { const ref = doc(db, "clips", code); const snapshot = await getDoc(ref); if (!snapshot.exists()) return setError("This clip does not exist."); const data = snapshot.data(); if (typeof data.expiresAt === "number" && Date.now() > data.expiresAt) return setError("This clip has expired."); setClip({ ...data, ref }); if (!data.protected) try { await updateDoc(ref, { views: increment(1) }); } catch {} } catch (err) { console.error(err); setError("Could not load this clip."); } finally { setLoading(false); } })(); }, [code]);
  async function unlock() { if (!password) return setError("Enter the password to unlock this clip."); setError(""); setUnlocking(true); try { const content = await decryptText(clip.content, password, clip.salt, clip.iv); setClip((c) => ({ ...c, content, unlocked: true })); try { await updateDoc(clip.ref, { views: increment(1) }); } catch {} } catch { setError("Incorrect password."); } finally { setUnlocking(false); } }
  async function copy() { if (!clip?.content || (clip.protected && !clip.unlocked)) return; try { await navigator.clipboard.writeText(clip.content); alert("Copied!"); } catch { alert("Could not copy the text."); } }
  if (loading) return <div className="app"><main className="container"><Header /><section className="card centered"><div className="loader"></div><p>Loading clip...</p></section></main></div>;
  if (error && !clip) return <div className="app"><main className="container"><Header /><section className="card centered"><div className="error-icon">!</div><h1>{error}</h1><button className="primary-button" onClick={onHome}>Create a new clip</button></section></main></div>;
  if (clip?.protected && !clip.unlocked) return <div className="app"><main className="container"><Header /><section className="card centered"><div className="lock-icon">🔒</div><span className="small-label">PROTECTED CLIP</span><h1>{code}</h1><p className="muted">Enter the password to decrypt this clip.</p><input className="unlock-input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && unlock()} placeholder="Password" autoFocus />{error && <div className="error">{error}</div>}<button className="primary-button create-button" onClick={unlock} disabled={unlocking}>{unlocking ? "Unlocking..." : "Unlock Clip"}</button><button className="text-button" onClick={onHome}>Create your own clip</button></section></main></div>;
  return <div className="app"><main className="container"><Header /><section className="card"><div className="clip-header"><div><span className="small-label">SHARED CLIP</span><h1>{code}</h1></div><span className="live-dot">LIVE</span></div><div className="content-box">{clip.content}</div><Countdown expiresAt={clip.expiresAt} /><button className="primary-button create-button" onClick={copy}>Copy Text</button><button className="text-button" onClick={onHome}>Create your own clip</button></section></main></div>;
}

function Countdown({ expiresAt }) { const [remaining, setRemaining] = useState(typeof expiresAt === "number" ? Math.max(0, expiresAt - Date.now()) : null); useEffect(() => { if (typeof expiresAt !== "number") return; const t = setInterval(() => setRemaining(Math.max(0, expiresAt - Date.now())), 1000); return () => clearInterval(t); }, [expiresAt]); if (expiresAt === null || typeof expiresAt === "undefined") return <div className="countdown">Never expires</div>; if (remaining <= 0) return <div className="countdown expired">Expired</div>; const total = Math.floor(remaining / 1000), m = Math.floor(total / 60), s = total % 60, h = Math.floor(m / 60), d = Math.floor(h / 24); const label = d ? `${d}d ${String(h % 24).padStart(2, "0")}h` : h ? `${h}h ${String(m % 60).padStart(2, "0")}m` : `${m}m ${String(s).padStart(2, "0")}s`; return <div className="countdown">Expires in <strong>{label}</strong></div>; }
function Header() { return <header className="header"><button className="logo" aria-label="ArchiClip home" onClick={() => { window.location.href = "/"; }}><img className="logo-image" src="/archiclip-logo.svg" alt="" aria-hidden="true" /><span>ArchiClip</span></button><span className="header-tag">Online Clipboard</span></header>; }
function Feature({ icon, title, text }) { return <div className="feature"><div className="feature-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div>; }
function Footer() { return <footer><span>ArchiClip</span><span>Temporary text sharing</span></footer>; }
export default App;
